spring:
  application:
    name: index-config-service
  # 配置文件所在git的地址
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/flyInTheSky123/springcloudconfig/
          search-paths: respo


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/