eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: index-gather-store-service
  #redis配置
  redis:
    #Redis数据库索引（默认为0
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 10
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池中的最小空闲连接
        max-idle: 8
        #连接超时时间（毫秒）
        min-idle: 0