eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: index-zuul-service
#网关，访问路径path 对应着 serviceId。path后面的参数根据实际访问填写
zuul:
  routes:
    api-a:
      path: /api-codes/**
      serviceId: INDEX-CODES-SERVICE
    api-b:
      # http://localhost:8051/backtest/simulate/000300
      path: /api-backtest/**
      serviceId: TREND-TRADING-BACKTEST-SERVICE
    api-c:
      path: /api-view/**
      serviceId: TREND-TRADING-BACKTEST-VIEW

  zipkin:
    base-url: http://localhost:9411

